### ISSUE TITLE
composer requirements

### ISSUE THREAD

**Issue by lowtower** [thecodingmachine/washingmachine#5]
Hi,

this project requires `m4tthumphrey/php-gitlab-api` in version `7.16` which is not available via composer.
Today (2017-04-27) only [version 7.15](https://packagist.org/packages/m4tthumphrey/php-gitlab-api) is available.

I followed the guide at the [www.codingmachine.com website](https://www.thecodingmachine.com/a-practical-guide-to-continuous-integration-in-php).
I get a composer error that `m4tthumphrey/php-gitlab-api` is not available.

Cheers,
LT.

**Comment by moufmouf** [comment]
Hey @lowtower ,

If you follow precisely the guide on the @thecodingmachine website, everything should work.

This works:
```
cd /root
composer create-project thecodingmachine/washingmachine --stability=dev
cd -
```

However, if you try to directly include "thecodingmachine/washingmachine" in your dev dependencies of your project, it will not work, unless you change your composer.json file to add a special repository that has a version 7.16 for php-gitlab-ci: https://github.com/thecodingmachine/washingmachine/blob/1.1/composer.json#L5-L10

This is because I have had to use a patched version the m4tthumphrey/php-gitlab-api to solve some bug and this version is not yet merged in the main project.

Let me know if this works.

**Comment by lowtower** [comment]
Thanks for Your reply.

Copied the files from Your gist - so I suppose everything is as You propose (double-checked).

I already copied the repo to my composer.json and then everything is fine ;-)

**Comment by lowtower** [comment]
You are right,
I had an error in my `composer.json` file.
Sorry for bothering You!
Cheers,
LT.
